import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const getDiscountPercentage = (price: number, salePrice: number) => {
  return Math.round(((price - salePrice) / price) * 100);
};

export const allProducts = [
  // Nicotine Pouches
  {
    id: 1,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },

  {
    id: 2,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 3,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 4,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 5,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 6,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 7,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 8,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 9,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 10,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 11,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 12,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 13,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 14,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
  {
    id: 15,
    name: "Klint Arctic Mint",
    category: "NICOTINE POUCHES",
    price: 4.99,
    salePrice: 3.6,
    rating: 4.8,
    brand: "Klint",
    image: "KLINT",
  },
];